"use client";

interface AISummaryProps {
  summary: string | null;
}

export function AISummary({ summary }: AISummaryProps) {
  if (!summary) return null;

  return (
    <div className="glass-card p-6 border-credex-800/25 relative overflow-hidden">
      {/* Subtle background glow */}
      <div className="absolute -right-16 -bottom-16 w-32 h-32 bg-credex-500/10 rounded-full blur-2xl pointer-events-none" />

      <div className="flex items-center gap-2 mb-3">
        <div className="px-2 py-0.5 bg-credex-50 border border-credex-200 rounded text-[10px] uppercase font-bold tracking-wider text-credex-900">
          AI Summary
        </div>
        <span className="text-[10px] text-navy-400 font-medium">Generated by Claude</span>
      </div>

      <p className="text-sm leading-relaxed text-navy-200 font-medium italic">
        &ldquo;{summary}&rdquo;
      </p>
    </div>
  );
}
